# Configuration for resource service.

runtime: python39
service: cron

# entrypoint: uvicorn --proxy-headers --port 8081 cron.app.main:app
entrypoint: gunicorn -c services/gunicorn_config.py --timeout 600 cron.app.main:app
# entrypoint: supervisord -c services/supervisor.conf

instance_class: B4_1G

# We need to specify basic scaling in order to use a backend instance class.
basic_scaling:
  max_instances: 20
  idle_timeout: 60m

# env_variables: